# Generated by Django 6.0 on 2025-12-16 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='DealRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('data_approved', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting', max_length=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
